### ISSUE TITLE
Voice Search Works but choosing the result does nothing

### ISSUE THREAD

**Issue by a-haan** [stari4ek/tvirl#1]
When voice searching for a channel, Google Assistant shows the desired Channel within the Live TV App.  Once I choose the result, the screen flashes as if it loads but it stays on the Channel that was already displaying.

I've tried this a few times and it has failed every time.

Using the Nvidia Shield on the latest firmware

**Comment by stari4ek** [comment]
Please send error report from TVirl's main menu with logs attached (automatically) - after getting this issue reproduced
