### ISSUE TITLE
Duplicated channels in genres

### ISSUE THREAD

**Issue by ncruces** [stari4ek/tvirl#10]
When you add group/category meta data to both the playlist (e.g. `group-title`) and the EPG (setting `category` for every `programme`) you get duplicated channels in the genres list.

**Comment by stari4ek** [comment]
Can you show example in Live Channels?
Please note that grouping is done per-programs (not per-channels). So, it's valid situation to have same programs in different genres

**Comment by ncruces** [comment]
I know that is valid, what I'm saying is the same channel shows up twice in one genre.
What would you want? A screenshot? A playlist/EPG demonstrating the issue?

**Comment by stari4ek** [comment]
> I'm saying is the same channel shows up twice in one genre.

hmm. will check. thx

**Comment by stari4ek** [comment]
Should be fixed in 0.4.3.1
