### ISSUE TITLE
info about tvirl logo in epg

### ISSUE THREAD

**Issue by peppesr** [stari4ek/tvirl#11]
haven't found a mail to contact you so i'm writing here. sorry.
just to know because the tvirl logo in the epg page is not in the correct selected row
![photo5873121577325933275](https://user-images.githubusercontent.com/1901507/67381737-b86eb380-f58c-11e9-89d7-2ed69e5821d3.jpg)
in the image "canale 5 mediaset" is highlighted but the tvirl logo is on "rai3" is just because it is in the first row of the page or else?
thanks a lot
Peppe

**Comment by stari4ek** [comment]
Hi.
Please note that this UI is fully implemented by system Live Channels App (Please check [FAQ](https://tvirl.app/faq))
I believe it shown only on first visible row to make overall look lightweight.
If you have multiple TV input sources - you will see a bit different behavior.
