### ISSUE TITLE
HLS: Single audio track only

### ISSUE THREAD

**Issue by guilhermy** [stari4ek/tvirl#13]
I don't know if this is related to TVirl or the Live Channel app: I have some channels with multiple audio tracks (like a dubbed and a original version), but in the options on the channel menu, where there's the Closed Caption,  PIP button, etc, the selection of audio track is always grayed out. It there a way around it?

**Comment by stari4ek** [comment]
This option becomes active when there're multiple audio tracks in stream.
you can check how TVirl identifies stream (it's tracks and so on) by enabling "Debug overview" from TVirl's context menu.

Also - please send error report from TVirl's settings after playing problematic stream.

**Comment by stari4ek** [comment]
TVirl supports multiple audio tracks, but `ExoPlayer` forces single audio track for muxed strean in `HLS`. `http progressive` and `HLS` with separated audio streams work well.
* https://github.com/google/ExoPlayer/issues/2014
* https://github.com/google/ExoPlayer/commit/3919843db27c78dc04ec498087182058393cced0

**Comment by stari4ek** [comment]
Workaround on TVirl side is planned

**Comment by stari4ek** [comment]
Implemented as part of 0.4.4.6
