### ISSUE TITLE
set VLC as default player in Live Channels

### ISSUE THREAD

**Issue by adelatour11** [stari4ek/tvirl#14]
Is it possible to set VLC as the default player in Live Channels instead of ExoPlayer ?
TS streams are not supported in Live Channels

**Comment by ghost** [comment]
Hey @adelatour11 I think this question should be asked to the Google devs https://play.google.com/store/apps/dev?id=5700313618786177705 instead of here. AFAIK Tvirl has no control of what player Live Channels use.

**Comment by adelatour11** [comment]
There is a feature call "Play with" in TVirl 
and i've checked that other media player can be chosen in tv input https://developer.android.com/training/tv/tif/tvinput 

Using VLC player as default would be a great help as some formats are not supported by exoplayer

**Comment by stari4ek** [comment]
Any playback options (exoplayer or VLC) should be adopted and integrated to `TV Input Service` (=_TVirl_) itself, not to Live Channels, cause all playback is handled by `TIS` (=_TVirl_).

"_Play with_" is feature of TVirl and it's not related to _Live Channels_/`TIS` in any way.

So, please specify which playback you're referring? _TVirl_'s playback inside _Live Channels_ or using "_Play With_", when _TVirl_ opens channel in external player?

In the case of "Play With" - you can mark any player you want as "default" and system will be opening it without asking to select player.

> TS streams are not supported in Live Channels

MPEG-TS are supported by ExoPlayer/TVirl. Please specify what exactly you're missing.

**Comment by adelatour11** [comment]
I am referring to TVirl's playback inside Live Channels
As VLC supports MPEG-TS, i'd like use VLC as TVirl's default playback inside Live Channels

**Comment by stari4ek** [comment]
> As VLC supports MPEG-TS, i'd like use VLC as TVirl's default playback inside Live Channels

This is incorrect. _ExoPlayer_ does support _MPEG-TS_ with _HLS_/_HTTP Progressive_ streams (https://exoplayer.dev/supported-formats.html)

So, please be more specific what exactly you think does not work with ExoPlayer. 

Anyway, VLC integration as playback backend is not planned for near future.

**Comment by adelatour11** [comment]
So I've just tested a mpeg-ts stream in tvirl and I have a 302 error when loading the stream

**Comment by stari4ek** [comment]
not sure what is "302" (_302 Found?_)
Please stop guessing and send error report after getting the issue from TVirl's main menu. I will check what exactly does not work for you

major part of channels played by TVirl is MPEG-TS (inside HLS, UDP/Multicast, HTTP-Progressive)

**Comment by adelatour11** [comment]
I found the solution

I had the 302 issue only with all the streams where address began with rtsp : 'rtsp://localip/fbxtv_pub/stream?namespace=1&service=201&flavour=hd' it is the standard url provided by my ISP for IPTV

I had to change all url to http, it works fine now

**Comment by stari4ek** [comment]
TVirl/ExoPlayer does not support **RTSP**.
This is special network protocol.

But it's a bit strange, cause TVirl shows specialized "not supported" error for RTSP/RTMP/Acestream.

if you send error report - i will check why exactly it did not show proper error and will fix in future releases
