### ISSUE TITLE
Buffer Size

### ISSUE THREAD

**Issue by Jayphen** [stari4ek/tvirl#15]
Is there any downside to setting the buffer size to 'huge'? My TV (Sony AF9) handles it fine, so I am wondering if there is some reason not to use that setting. Will it make channels load slower initially?

**Comment by stari4ek** [comment]
@Jayphen, it defines how much data should TVirl to buffer before it starts playing or restart playing after buffering. So, if connection i slow - it could make channels load slower. But it really depends on the network bandwidth: your and service.
Plus if it's UDP/Multicast or HTTP Progressive - due the nature of streams (it's live) - you should see slight slowness, cause server sends data partially. HLS should be fine
