### ISSUE TITLE
Losing sources configuration

### ISSUE THREAD

**Issue by eSoares** [stari4ek/tvirl#20]
Hello,

I'm not sure if this is a TVirl or Live channels issue, but I'm happy to help debug the issue or close it if you think is out of scope.
I have notice this happening twice in a month, the Live Channels app loses the source configuration. Not sure what caused it.

One of my theories is that TVirl tried to update the playlist, and due to connectivity issues reported an empty playlist/no channels. Latter on a new update the channels where back and live channels had lost all the channel selection. 
Is it possible for this to be the case?

If there is any logs that can help investigate the cause of this, I will be happy to collect and analyse them.
From what I have seen no updates where made in the live channels app or TVirl before the events.

**Comment by stari4ek** [comment]
Sorry for late response.

Yeah, Live Channels disables all newly added channels if it's not initial installation. So if TVirl removes channels and add them after - you will get this kind of situation.

please send error report from TVirl's main menu after getting this issue again.
