### ISSUE TITLE
Size of logo inserted in database is big

### ISSUE THREAD

**Issue by vJoe19** [stari4ek/tvirl#22]
Hi observed that  the size of each logo inserted in the field in TvContract.Channels.Logo.CONTENT_DIRECTORY in TvContract.Channels table is big(around 2.5MB). If each logo size is around 2MB then installing 10000 channels will consume large size of space and increase the database size. 
My suggesstion is why can't the logos can be compressed  to  kilobytes instead of storing such huge information in the database.

**Comment by stari4ek** [comment]
Hi,

Which version of TVirl are you referring?
Starting I believe 0.4.4.5 (+-) TVirl resizes images to fit into 256px x 256px. And decodes them to PNG.
Same work is performed by AOSP implementation of TvStorage (which is missing for Sony at least).

How did you measure it? I'd expect that resized/decoded images should be smaller than 2Mb in average

**Comment by stari4ek** [comment]
I've checked some perf stats from logo processing.
Some "tvpremiumhd" service playlist:
- logo added (median): 1212
- bytes written (median): 18,853,885

So, on average it should be: 16kb per logo.

**Comment by stari4ek** [comment]
@vJoe19 , if you can provide some additional information please comment here
