### ISSUE TITLE
"#EXTVLCOPT:"can't work normally in 0.4.5.0

### ISSUE THREAD

**Issue by VirgilClyne** [stari4ek/tvirl#24]
For example : 
"#EXTVLCOPT:http-referrer=" and "#EXTVLCOPT:http-user-agent=" in m3u8 can't work in 0.4.5.0

And I can't use "#EXTVLCOPT:aspect-ratio=16:9" force the source aspect ratio in any version

Device: MiBox S
Android TV 9.0

**Comment by stari4ek** [comment]
> And I can't use "#EXTVLCOPT:aspect-ratio=16:9" force the source aspect ratio in any version

this is expected behavior. forcing aspect-ratio works from settings only.

> "#EXTVLCOPT:http-referrer=" and "#EXTVLCOPT:http-user-agent=" in m3u8 can't work in 0.4.5.0

need to check.
There were changes related to `#EXTVLCOPT` (did not load tag from header)

**Comment by stari4ek** [comment]
non-working `user-agent` should be fixed with build 1964 for 0.4.5.0.

BTW, `http-referrer` never worked for TVirl. Do you really need it?
Any other http headers?

**Comment by stari4ek** [comment]
New feature requests for `http-referrer` and `aspect-ratio` were created.
Will close this issue since `User-Agent` issue is fixed

**Comment by stari4ek** [comment]
FYI, `#EXTVLCOPT:http-referrer` will be supported starting from 0.4.5.2

**Comment by SlazE888** [comment]
Михаил, когда ждать атрибут aspect-ratio?

**Comment by stari4ek** [comment]
> Михаил, когда ждать атрибут aspect-ratio?

Думаю каналы 4:3 умрут быстрее.
Конкретных планов нет и есть много более приоритетных задач
