### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by izidan** [stari4ek/tvirl#3]
Seems to have issues with https stream over self-signed certificates, other apps works fine though.

**Comment by stari4ek** [comment]
Please note, that "self-signed" certificates are not fully valid certificates.
Ability to ignore SSL certificate issues is in TODO: stari4ek/iptv-for-androidtv#1349

**Comment by stari4ek** [comment]
Ability to ignore issues with certificates was added in 0.4.2.1
It can be enabled in TVirl's "Expert" settings for 1 month.

Please note that this is insecure practice. TVirl does not differentiate reasons (self-signed, expired, bad ciphers, ...), so all SSL issues are ignored

**Comment by izidan** [comment]
thanks for the fix, looking forward for testing it.

What is `1 month` comment about?

**Comment by stari4ek** [comment]
> What is 1 month comment about?

Suppressing SSL errors works for 1 month from the moment this option is enabled.
After 1 month this option should be enabled once again.
