### ISSUE TITLE
Failed to install playlist on Mibox S

### ISSUE THREAD

**Issue by fizrierahaman** [stari4ek/tvirl#31]
Hello, just recently i'm unable to reload the playlist. Display message 'Failed to install playlist' Error 'Connection Failed'

I'm using TVirl on my Mibox S

**Comment by stari4ek** [comment]
Double check that you're using valid playlist. Just try to load it in desktop browser.
If it works well but failing in TVirl - please send error report from TVirl's main menu

**Comment by fizrierahaman** [comment]
Tried reinstall apps and reload the playlist. Now it's working fine. Issue closed
