### ISSUE TITLE
Feature: Ability to map categories from playlist to genres

### ISSUE THREAD

**Issue by guilhermy** [stari4ek/tvirl#4]
Sorry if this is not the right place for suggestions.

I'd like to start by saying that I just love how this app integrates with the Android TV, it really is wonderful to use it. Great job! I'm already a subscriber.

I don't know if it would be feaseable, but I would like to make a suggestion for the categories.
It would be really good if the app could translate categories from my list to the ones available with android tv. Something like:
I could set all my categories labeled with "Action movies" to be translated to the android string "MOVIES". Or "Drama movies" to "DRAMA", etc.

The only way I was able to do this is manually with a text editor. But it really is a pain to redo the same everytime my list gets updated with new channels. If we could preset some categories to be automatically translated it would be awsome.

**Comment by stari4ek** [comment]
Thank you for your feedback.
Exact functionality (categories mapping) is in TODO list: stari4ek/iptv-for-androidtv#1609

**Comment by ncruces** [comment]
PVR Live has an interesting mapping:
https://sites.google.com/view/pvrlive/playlist/playlist-genres

**Comment by stari4ek** [comment]
it can work. For some. But any hard-coded mapping won't work well with i19n and lots and lots of other cases.

**Comment by stari4ek** [comment]
Will be released with 0.4.4.0
