### ISSUE TITLE
[Bug] No video with MPEG-2 SD sources

### ISSUE THREAD

**Issue by lars18th** [stari4ek/tvirl#40]
Hi,

I tested this with some FTA programs from a DVB tuner in MPEG-2 SD format sended as a TS continous streaming (MPEG-TS Progressive HTTP live, where the source is one SAT>IP server). When selecting these channels nothing is shown... I tested:

1. Change from HW to HW+SW decoders and SW only. Nothing changes: black screen.
2. "Play with..." inside the tvirl menu and selecting VLC, then the channel is played without troubles.
3. Using other similar TV listings Apps linked to Live Channels: in this case the program is played without any problem.

Please, take note that from the same source all H.264 HD channels are played with no problems using tvirl. So, the question is: are MPEG-2 SD sources supported or not?

**Comment by lars18th** [comment]
Hi @stari4ek ,

Please, can you confirm if the MPEG-2 codec is supported or not?

**Comment by stari4ek** [comment]
mpeg-2 is supported as long as system has appropriate decoder. Google does not require from OEMs to bundle decoder for MPEG2.
Decoder settings in TVirl changes audio dedoder selection only.

Please send error report from TVirl's main menu after trying to attempt problemmatic channel

**Comment by lars18th** [comment]
Hi @stari4ek ,

I'm using CCWGTV as system. Perhaps it doesn't have MPEG-2 hardware decoding support, However, why you not decode it using Software? Using VLC it works without troubles, so.MPEG-2 software video decoding can be done in this hardware without problems. And as far as I know, the ExoPlayer can decode MPEG-2 VIDEO in software.

**Comment by stari4ek** [comment]
> And as far as I know, the ExoPlayer can decode MPEG-2 VIDEO in software.

nope.
ExoPlayer has software decoders for audio only (via ffmpeg).
Please check ExoPlayer's comment here: https://github.com/google/ExoPlayer/issues/2069#issuecomment-260890480
