### ISSUE TITLE
Bug? Info about the url-tvg tag

### ISSUE THREAD

**Issue by lars18th** [stari4ek/tvirl#43]
Hi @stari4ek ,

I readed the wiki at this point: https://github.com/stari4ek/tvirl/wiki/M3U#m3u-header
And this response regarding one issue: https://github.com/stari4ek/tvirl/issues/32#issuecomment-655401003

But I'm not sure about the current behaviour of the EPG reading. Please, can you explain these questions?
- If the M3U list includes in the first line a header like `#EXTM3U url-tvg="https://..."` then this EPG is **always** used?
- Or the `url-tag` is only used when configuring the list?

I ask about this because I done some changes in my M3U list, but the new values are not used. Only the values configured in the list about the EPG sources are in use.

So, if you use this header only one time: why not add a button to "re-read" this tag and generate new entries for the EPG sources? Or you use this tag header every time the list is reloaded?

Please, provide more information.
Thank you.

**Comment by stari4ek** [comment]
TVirl reads `url-tvg` during playlist initial setup and automatically add it to playlist configuration.
You can add/remove/replace this EPG during initial setup and this list will be remembered for any further updates.

So, TVirl does not track changes in `url-tvg` and uses what was selected during initial setup.

If you updated `url-tvg` in the playlist - you can edit current playlist settings via TVirl's UI and edit url for assigned EPG.
Or you can start new playlist configuration and TVirl will read new value for EPG and pre-fill it by default.

**Comment by lars18th** [comment]
Hi @stari4ek ,

Thank you for the information. It's now very clear. However I suggest these two actions:
1. Put this information inside the Wiki.
2. Add one manual option to "reload EPG inside the list". The code is just the same as now, you only need to call to the same function that creates the EPG entries after clearing them. Remember that's quite difficult to write URL's with a remote RC. And a simple _reload button_ is more user friendly.

I hope you want to consider these two suggestions.
Thank you for listening us!
