### ISSUE TITLE
[Request] EPG comestic enhancements

### ISSUE THREAD

**Issue by lars18th** [stari4ek/tvirl#44]
Hi,

This is partially based on my first request #39. And are some new _small_ enhancements to improve the EPG:

- Add the option of _cut_ larges lines in description metadata (`desc` tag). Some EPG providers put large texts in this field. And inside the Live Channels player it's impossible to see all the content. However, some put almost one (or more) _line breaks_. For example, in the first line you can see the YEAR, SOURCE, RATING, DIRECTOR, etc. And in the second line you can see the ARGUMENT. Then assuming that the Live Channels can show only two lines, if the first is very large then you can't see anything about the second. So the request is to **cut the first line up to N characters**. You can detect the line break as `\r\n` or similar. So you only need to define the size of charactes before the line cut.
- Similar to the previous, if the sub-title is very long, then the Live Channels, instead of print it join to the title, it uses the first line of the description. So a similar problem appears. So the second suggestion is to cut the subtitle too (based on the lenght of the title+subtitle).
- A third suggestion is about how to print the sub-title. I observed using the PlutoTV channels, that in the EPG inside the Live Channels the Title is printed in bold (like does TVirl), but the sub-title is done in plain. So it's easy to identify it in the Title, as you see: "**Title**. Subtitle". But now using the TVirl you see "**Title. Subtitle**". Perhaps you feel this cosmetic change is not relevant, but it improves the readability, and it can be done as the PlutoTV EPG can do it using the standard interface.

I hope these enhancements can be considered by the author.
Thank you for your effort.
Regards.

**Comment by stari4ek** [comment]
There is some processing of titles/sub-titles/description already done by TVirl according to some recommendations from TIF (`TvContract.ProgramColumns.COLUMN_SHORT_DESCRIPTION`)
> It is recommended to limit the length of the descriptions to 256 characters.

> Add the option of cut larges lines in description metadata (desc tag). Some EPG providers put large texts in this field. And inside the Live Channels player it's impossible to see all the content. However, some put almost one (or more) line breaks. For example, in the first line you can see the YEAR, SOURCE, RATING, DIRECTOR, etc. And in the second line you can see the ARGUMENT. Then assuming that the Live Channels can show only two lines, if the first is very large then you can't see anything about the second. So the request is to cut the first line up to N characters. You can detect the line break as \r\n or similar. So you only need to define the size of charactes before the line cut.

Sorry, but tuning processing for one specific use case is not an option here. Different EPG providers fill title/su-title/description differently. What works in one case will break another one.
On top of that there are other TV Apps (Sony TV's for example), which expose much larger description in it's details panel.

> Similar to the previous, if the sub-title is very long, then the Live Channels, instead of print it join to the title, it uses the first line of the description. So a similar problem appears. So the second suggestion is to cut the subtitle too (based on the lenght of the title+subtitle).
> A third suggestion is about how to print the sub-title. I observed using the PlutoTV channels, that in the EPG inside the Live Channels the Title is printed in bold (like does TVirl), but the sub-title is done in plain. So it's easy to identify it in the Title, as you see: "Title. Subtitle". But now using the TVirl you see "Title. Subtitle". Perhaps you feel this cosmetic change is not relevant, but it improves the readability, and it can be done as the PlutoTV EPG can do it using the standard interface.

Current title/sub-title/description (short/full) processing will be reviewed, but this proposal is focused on specific cases which may not be suitable for general audience (different TV Apps, different EPG providers)

**Comment by lars18th** [comment]
Hi @stari4ek ,

OK. No problem at all. I appreciate that you want to at least review it. You know best the problems with different implementations. My aim is only to make some suggestions for improvement. Good job! :+1: 

Regards.
