### ISSUE TITLE
How to refresh channel logos?

### ISSUE THREAD

**Issue by lars18th** [stari4ek/tvirl#46]
Hi,

I know that the Live Channels is outside the TVirl App. However, the developer of it has interesting information in the Wiki. Today I have detected one trouble: If I update the channel icon (not the source, but the file; so identical URL), and I clean the channel list, then the ICON _inside_ the Live Channels Guide is not updated. Any idea?

Thank you.

**Comment by stari4ek** [comment]
Hi,

There are some caching applied on TVirl side and Live Channels app.

1. TVirl caches **channels** logo. These are logos used in top banner when switching channels and on left side in the EPG interface. If link is the same - TVirl will not check if it was updated
2. Live Channels app caches **programs** logo. There are logos you can see as recent in Live Channels context menu, in EPG per-program info.

To reset (1) caching - just "clean all" from TVirl's menu and "reload current playlist" to re-fill all info back. You can add get parameter to the URL which will be ignored by your server, but the url will be different (for. ex: `?fake_param=123`)
To reset (2) caching - you can clean Live Channels app's data from system settings. BTW I'd expect that it should self-update if you serve your logo using proper http caching headers

**Comment by lars18th** [comment]
Thank you!
Your two suggestions are useful.
Regards.
