### ISSUE TITLE
Supporting DRM in clearkey mode?

### ISSUE THREAD

**Issue by 0x15f2d** [stari4ek/tvirl#53]
here's a snippet of the program
```
#EXTINF:-1 tvg-id="id" groups="ANDROID_CATEGORY" group-title="Category" tvg-logo="http://domain/logo.png",Channel
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=cleartext
#KODIPROP:inputstream.adaptive.license_key=https://domain/key.php?kid={uuid1}&key={uuid2}
https://domain/channel.mpd
```

key from api:
```

{  
   "keys":[  
      {  
         "kty":"oct",
         "k":"base64key1",
         "kid":"base64key2"
      }
   ],
   "type":"temporary"
}
```

as stated. a lot of channels having this kind of DRM lying around but seems like this app can't decode it yet. will it be supported in the future?

**Comment by Harshit0755** [comment]
True, would be better if it supports this format as well

**Comment by RayvChan** [comment]
also HLS and HSS content with clearkey

**Comment by marksdemellin** [comment]
any news on support to clearkey?

**Comment by stari4ek** [comment]
@marksdemellin, working on it. Should be available as part of next alpha soon.

**Comment by stari4ek** [comment]
Initial support for ClearKey was added as part of 0.5.4.0 (should be available in alpha very soon).
[Supports](https://github.com/stari4ek/tvirl/wiki/M3U#drm):
- ClearKey with license url
- local ClearKey for DASH, using `kid:key` (hex, base64url), json

If there are ClearKey streams, which work in other players for you, but TVirl fails to play them on 0.5.4.0+ version - please reach me (tvirl bug report or telegram. I will need links/keys from you)
