### ISSUE TITLE
Colorization in EGP view ?

### ISSUE THREAD

**Issue by TopperBG** [stari4ek/tvirl#56]
Am I wrong, but I recall in EPG view on my Sony TV with Tvirl integrated colorization of groups of channels?
Now I'm useing same m3u list but don't see any colors and it's hard to find music or sport or anime channels.
Was there colorization anytime in Tvirl ?

**Comment by stari4ek** [comment]
Sony TV app colorizes channels using there "genres".
"Genres" can be automatically pre-selected by TVirl if there is exact match of channel group name (see https://github.com/stari4ek/tvirl/wiki/M3U#grouping). Otherwise there is an option to set genre explicitly during playlist configuration.
