### ISSUE TITLE
Sony: channel's banner is not hidden

### ISSUE THREAD

**Issue by stari4ek** [stari4ek/tvirl#8]
Device:
```
System: 3.10.79 (665201)
Sdk: 26
Device: BRAVIA_ATV2
Product: BRAVIA_ATV2_EU
Manufacturer: Sony
Model: BRAVIA 4K GB
```
As reported by user, this issue was introduced with system update to 8.0 and it's reproduced in Sony's TV App only

**Comment by SlazE888** [comment]
Это не так(на моём BRAVIA 4K GB ATV3 sdk 26). Баннер исчезает автоматически через 4(10) секунды или вообще не появляется если соответствующая настройка отключена в AndroidTV v8. А вот как раз в программе Live Channels после переключения канала, автоматически через несколько секунд, информационный баннер о передаче не закрывается!

**Comment by blrB** [comment]
Репортером ,бага на 4pda (https://4pda.ru/forum/index.php?showtopic=725422&st=4380#entry88035560) был я. Сейчас проверил, баннер пропадает (раньше не пропадал). Sony XE8096 Android TV v8.
